### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by hansegucker** [tylerwince/flake8-bandit#25]
A new release on PyPI would be very welcome, so we can used the fixed flake8-bandit compatible with the newest version of bandit.

**Comment by sathieu** [comment]
it looks like 3.0.0 was just released. There is no indication of backward incompatible changes. @tylerwince Why the major version bump?

**Comment by skwashd** [comment]
3.0.0 is now on PyPI - see https://pypi.org/project/flake8-bandit/#history

4.1.x is coming soon.
