### ISSUE TITLE
What is the difference between using bandit directly and your library?

### ISSUE THREAD

**Issue by slidenerd** [tylerwince/flake8-bandit#34]
Mind adding a few sentences to the doc about any advantages or differences your library has over using bandit directly?

**Comment by copdips** [comment]
I've the same question, but at least vscode suggests to use this extension in favor of original bandit, also with no reason:
https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions#alternatives-for-deprecated-settings--
