### ISSUE TITLE
[Request] Would it be possible to make a new release to PyPI?

### ISSUE THREAD

**Issue by davfsa** [tylerwince/flake8-bandit#38]
I have noticed that the project currently says it is on version `4.1.0`, and there is a tag and GitHub release with the same name, but there hasn't been a release on PyPI since `3.0.0`.

There seems to be a release CI setup, but it hasnt really worked from a quick look at the past runs. I will try to see the following days anything needs to be done to fix it (if its even broken).

Making this quick issue to bring it to your attention :)

**Comment by skwashd** [comment]
That's my fault. The release action was buggy. It is fixed in #39. Once that is merged and v4.1.1 is tagged it should push a release to PyPI automagically.

**Comment by skwashd** [comment]
@davfsa the CI fix was merged abd 4.1.1 is now available on pypi.

**Comment by davfsa** [comment]
Tysm!
